# Generated by Django 4.1 on 2022-09-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repoAstro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_ite', models.CharField(max_length=30)),
                ('solucion_inicial', models.CharField(max_length=30)),
                ('solucion_final', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('id_algo_opti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repoAstro.algo_opti')),
                ('id_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repoAstro.dataset')),
                ('id_prob_opti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repoAstro.prob_opti')),
            ],
        ),
    ]
