# Generated by Django 4.1 on 2022-09-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoAstro', '0005_alter_solucion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solucion',
            name='solucion_final',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='solucion_inicial',
            field=models.CharField(max_length=1000),
        ),
    ]
